# Generated by Django 6.1.1 on 2026-09-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('stress_burnout', 'Стресс и выгорание'), ('emotional_health', 'Эмоциональное здоровье'), ('sleep', 'Сон'), ('time_management', 'Тайм-менеджмент'), ('exam_prep', 'Подготовка к экзаменам'), ('communication_conflicts', 'Общение и конфликты'), ('work_rest_balance', 'Баланс работы и отдыха'), ('asking_for_help', 'Как попросить о помощи')], max_length=32)),
                ('audience', models.CharField(choices=[('schoolchild', 'Школьник'), ('student', 'Студент'), ('adult', 'Взрослый'), ('all', 'Все')], default='all', max_length=16)),
                ('read_minutes', models.PositiveSmallIntegerField(default=5)),
                ('body', models.TextField()),
                ('practice_5min', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True)),
            ],
        ),
    ]
