# Generated by Django 6.1.1 on 2026-09-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyPoint',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(choices=[('school', 'school'), ('kindergarten', 'kindergarten'), ('university', 'university'), ('college', 'college'), ('stadium', 'stadium'), ('arena', 'arena')], max_length=20)),
                ('source', models.TextField()),
                ('geocode_confidence', models.FloatField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('geocode_method', models.CharField(blank=True, default='', max_length=32)),
                ('geocode_provider', models.CharField(blank=True, default='', max_length=32)),
                ('geocode_note', models.TextField(blank=True, default='')),
            ],
        ),
    ]
