# Generated by Django 6.1.1 on 2026-09-22 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('q1', models.PositiveSmallIntegerField(choices=[(0, 'Никогда / почти никогда'), (25, 'Редко'), (50, 'Иногда'), (75, 'Часто'), (100, 'Всегда')])),
                ('q2', models.PositiveSmallIntegerField(choices=[(0, 'Никогда / почти никогда'), (25, 'Редко'), (50, 'Иногда'), (75, 'Часто'), (100, 'Всегда')])),
                ('q3', models.PositiveSmallIntegerField(choices=[(0, 'Никогда / почти никогда'), (25, 'Редко'), (50, 'Иногда'), (75, 'Часто'), (100, 'Всегда')])),
                ('q4', models.PositiveSmallIntegerField(choices=[(0, 'Никогда / почти никогда'), (25, 'Редко'), (50, 'Иногда'), (75, 'Часто'), (100, 'Всегда')])),
                ('q5', models.PositiveSmallIntegerField(choices=[(0, 'Никогда / почти никогда'), (25, 'Редко'), (50, 'Иногда'), (75, 'Часто'), (100, 'Всегда')])),
                ('q6', models.PositiveSmallIntegerField(choices=[(0, 'Никогда / почти никогда'), (25, 'Редко'), (50, 'Иногда'), (75, 'Часто'), (100, 'Всегда')])),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
