# Generated by Django 6.1.1 on 2026-09-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familygroup',
            name='meeting_point_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
